<?php
require_once("config.php");

echo "<!DOCTYPE html>\r\n";
echo "<html>\r\n";
echo "<head>\r\n";
echo "<meta name='viewport' content='width=device-width, initial-scale=1'>";
echo "<meta name='apple-mobile-web-app-capable' content='yes' />";
echo "<link rel='stylesheet' href='//code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.css' />";
echo "<link rel='styleSheet' href='$rootserver/$installfolder/mobile.css' type='text/css'/>\r\n";

echo "<link rel='apple-touch-icon' href='https://brax.me/img/brax-icon.png'> ";
echo "<link rel='apple-touch-startup-image' href='../img/brax-icon.png' />";


echo "<script src='//code.jquery.com/jquery-1.8.2.min.js'></script>";
echo "<script src='../libs/jquery-cookie-master/jquery.cookie.js'></script>\r\n";
echo "<script src='//code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.js'></script>";
 ?>
