<?php
require_once("config.php");

if(!isset($_SESSION['language'])){
    $_SESSION['language']='';
}
if($_SESSION['language']==''){
    $_SESSION['language']='english';
}

    $menu_handle = 'Username';
    $menu_home = 'Home';
    $menu_rooms = 'Rooms';
    $menu_room = 'Room';
    $menu_live = 'Live';
    $menu_chats = 'Chats';
    $menu_chat = 'Chat';
    $menu_people = 'People';
    $menu_settings = 'Settings';
    $menu_activity = 'Activity';
    $menu_logout = 'Logout';
    $menu_restart = 'Restart';
    $menu_myprofileandfiles = 'My Profile, Photos, and Files';
    $menu_myprofile = 'My Profile';
    $menu_userprofile = "User Profile";
    $menu_myphotos = 'My Photos';
    $menu_myfiles = 'My Files';
    $menu_myrooms = 'My Rooms';
    $menu_whatsnew = "What's New";
    $menu_password ='Password';
    $menu_confirmpassword ='Confirm Password';
    $menu_changepassword ='Change Password';
    $menu_techsupport ='Tech Support';
    $menu_myaccountinfo = 'My Account Settings';
    $menu_colortheme = 'Color Theme';
    $menu_language = 'Language';
    $menu_edit = 'Edit';
    $menu_public = 'Public';
    $menu_community = 'Contacts';
    $menu_top = 'Top';
    $menu_roomselect = 'Select Room';
    $menu_discoverrooms = 'Discover Rooms';
    $menu_trending = 'Trending';
    $menu_communitylist = 'Group Lists';
    
    $menu_myidentity = 'My Identity';
    $menu_mynotifications = 'My Notifications';
    $menu_advancedsettings = 'Advanced Settings';
    $menu_save = "Save Changes";
    $menu_managerooms = "Manage Rooms";
    $menu_manageroom = "Manage Room and Members";
    $menu_websites = "Websites";
    $menu_all = "All";
    $menu_activetoday = "Active Today";
    $menu_sharefile = "Share File";
    $menu_photos = "Photos";
    $menu_sharephoto = "Share Photo";
    $menu_uploadphoto = "Upload Photo";
    $menu_uploadfile = "Upload File";
    $menu_delete = "Delete";
    $menu_addparty = "Add Party";
    $menu_station = "Station";
    $menu_startstation = 'Start Station';
    $menu_find = "Find";
    $menu_leave = "Leave";
    $menu_back = "Back";
    $menu_hide = "Hide";
    $menu_gotoroom = "Go to room to post";
    $menu_name = 'Name';
    $menu_email = 'Email';
    $menu_alias = 'External Alias';
    $menu_platformtour = 'Platform Tour';
    $menu_termsofuse = 'Terms of Use';
    $menu_privacy = 'Privacy Policy';
    $menu_tokenactivity = 'Token Activity';
    $menu_tokenstore = 'Token Store';
    $menu_sound = 'Sound';
    $menu_deviceinfo = 'User Device Info';
    
    $menu_tokens = 'Tokens';
    $menu_gift = 'Kudos!';
    $menu_thanks = 'Thanks!';
    
    $menu_whoshere = "Who's Here";
    $menu_roommembers = "Room Members";
    $menu_aboutme = "About Me";
    $menu_managesocialvision = "Manage $enterpriseapp";
    $menu_upgrade = "Upgrade to $enterpriseapp";
    $menu_manageupgrade = "$appname Services Store";
    $menu_setprofilephoto = "Set a Profile Photo";    
    $menu_biography = "Profile";
    $menu_biographyprompt = "Brief Biography";
    $menu_refresh = "Refresh";
    $menu_title = 'Title';
    $menu_newtopic = "New Topic, comment, link, photos, video";
    $menu_reply = "Topic Reply";
    $menu_replies = "Comments";
    $menu_roomfiles = "Room Files";
    $menu_roominvite = "Invite";
    $menu_roomunsubscribe = "Unsubscribe from Room";
    $menu_mutenotifications = "Mute Notifications";
    $menu_unmutenotifications = "Enable Notifications";
    $menu_showoldermessages = "Show Older Messages";
    $menu_hideoldermessages = "Hide Older Messages";
    $menu_displayinglast = 'Displaying Last';
    $menu_messages = 'Messages';    
    $menu_message = 'Message';    
    $menu_selectfile = 'Select File';
    $menu_selectphoto = 'Select Photo';
    $menu_takephoto = 'Take Photo';
    $menu_members = 'Members';
    $menu_pinned = 'Pinned';
    $menu_more = 'More';
    $menu_cancel = 'Cancel';
    $menu_startchat = 'Start Chat';
    $menu_resumechat = 'Resume Chat';
    $menu_block = 'Block';
    $menu_unblock = 'Unblock';
    
    $menu_signup = 'Sign Up';
    $menu_accept = 'I accept the';
    $menu_createaccount = 'Create Account';
    $menu_login = 'Login';
    $menu_forgotpassword = 'Forgot Password';
    $menu_join = 'Join';
    $menu_existingaccount = 'Already have an account?';
    $menu_or = 'or';
    $menu_e2ekey = 'E2E Secret Passkey - Optional';
    $menu_friends = "Friends";
    $menu_friendadd = "Add Friend";
    $menu_frienddelete = "Remove Friend";
    $menu_roomfavorite = "Add to Favorites";
    $menu_roomfavoritedelete = "Remove from Favorites";
    $menu_roomfavorites = "Favorite Rooms";
    $menu_new = "New";
    $menu_newfolder = "New Folder";
    $menu_sortbydate = "By Date";
    $menu_sortbyname = "By Name";
    $menu_sortbysize = "By Size";
    $menu_filename = "File Name";
    $menu_download = "Download";
    $menu_mysharedphotos = "My Shared Photo Albums";
    $menu_lock = "Lock";
    $menu_follow = "Follow";
    $menu_unfollow = "Unfollow";
    $menu_followers = "Followers";
    $menu_following = "Following";
    $menu_postsfollowing = "Notifications from Followed Only";

    $menu_signupsuccess = "Done! Please Login to continue.";
    $menu_signupsuccess2 = "Download the $appname mobile app from your app store for a better experience.";
    $menu_techsupportfaq = "FAQ Tech Support";
    $menu_sms = "Mobile Phone";
    
if($_SESSION['language']=='spanish'){

    $menu_handle = 'Nombre de Usuario';
    $menu_home = 'Inicio';
    $menu_rooms = 'Salas';
    $menu_room = 'Sala';
    $menu_live = 'Canal';
    $menu_chats = 'Chat';
    $menu_chat = 'Chat';
    $menu_people = 'Gente';
    $menu_settings = 'Configuración';
    $menu_activity = 'Notificationes';
    $menu_logout = 'Cerar Sesion';
    $menu_restart = 'Reiniciar';
    $menu_myprofileandfiles = 'Mi Pagina, Fotos y Archivos';
    $menu_myprofile = 'Mi Pagina';
    $menu_userprofile = "Perfil de Usuario";
    $menu_myphotos = 'Mis Fotos';
    $menu_myfiles = 'Mis Archivos';
    $menu_myrooms = 'Mis Salas';
    $menu_whatsnew = "Que hay de Nuevo";
    $menu_password ='Contraseña';
    $menu_confirmpassword ='Confirma Contraseña';
    $menu_changepassword ='Cambiar Contraseña';
    $menu_techsupport ='Soporte Técnico';
    $menu_myaccountinfo = 'Mi Información';
    $menu_colortheme = 'Tema del Color';
    $menu_language = 'Idioma Language';
    $menu_edit = 'Editar';
    $menu_public = 'Público';
    $menu_community = 'Communidad';
    $menu_top = "Honores";
    $menu_roomselect = 'Selección de Salas';
    $menu_discoverrooms = 'Discubre Salas';
    $menu_trending = 'Popular';
    $menu_communitylist = 'Lista de la Communidad';
        
    $menu_myidentity = 'Mi Identificación';
    $menu_mynotifications = 'Mis Notificaciónes';
    $menu_advancedsettings = 'Configuración Avanzado';
    $menu_save = "Guardar Cambios";
    $menu_managerooms = "Manejar los Salas";
    $menu_manageroom = "Manejar un Sala y Miembros";
    $menu_websites = "Los Sitios Web";
    $menu_all = "Todos";
    $menu_activetoday = "Hoy en Dia";
    $menu_sharefile = "Compartir Archivo";
    $menu_photos = "Fotos";
    $menu_sharephoto = "Compartir Foto";
    $menu_uploadphoto = "Cargar Foto";
    $menu_uploadfile = "Cargar Archivo";
    $menu_delete = "Borre";
    $menu_addparty = "Agregar Persona";
    $menu_station = "Canal";
    $menu_startstation = 'Commenzar Canal';
    $menu_find = "Acerta";
    $menu_leave = "Deje";
    $menu_back = "Regresa";
    $menu_hide = "Esconde";
    $menu_gotoroom = "Va a la sala para publicar";
    $menu_name = 'Nombre';
    $menu_email = 'Correo Electronico';
    $menu_alias = 'Alias';
    $menu_platformtour = 'Toro de la Plataforma';
    $menu_termsofuse = 'Condiciónes de Uso';
    $menu_privacy = 'Politica de Privacidad';
    $menu_tokenactivity = 'Actividades de Token';
    $menu_tokenstore = 'Tienda de Token';
    $menu_sound = 'Sonido';
    $menu_deviceinfo = 'Dispositivo Móvil';
    
    $menu_tokens = 'Tokens';
    $menu_gift = 'Kudos!';
    $menu_thanks = 'Gracias';
    
    $menu_whoshere = "Que Esta Aqui";
    $menu_roommembers = "Miembro de Sala";
    $menu_aboutme = "Sobre Mi";
    $menu_managesocialvision = "Manejar $enterpriseapp";
    $menu_upgrade = "Actualice Mi Cuenta";
    $menu_setprofilephoto = "Establecer una Foto de Perfil";    
    $menu_biography = "Biografia";
    $menu_biographyprompt = "Biografia";
    $menu_refresh = "Refresca";
    $menu_title = 'Titulo';
    $menu_newtopic = "Nuevo Tema - commentario, enlace, foto, video";
    $menu_reply = "Responde al Tema";
    $menu_replies = "Respuestas";
    $menu_roomfiles = "Archivo de Salas";
    $menu_roominvite = "Invitación";
    $menu_roomunsubscribe = "Sal de esta Sala";
    $menu_mutenotifications = "Silencia Notificaciones";
    $menu_unmutenotifications = "Permita Notificaciones";
    $menu_showoldermessages = "Mostrar Mensajes Antiguos";
    $menu_hideoldermessages = "Esconde Mensajes Antiguos";
    $menu_displayinglast = 'Mostrando los últimos';
    $menu_messages = 'mensajes';    
    $menu_message = 'Mensaje';    
    $menu_selectfile = 'Selecciona Archivo';
    $menu_selectphoto = 'Selecciona Foto';
    $menu_takephoto = 'Toma Foto';
    $menu_members = 'Miembros';
    $menu_pinned = 'Fijado';
    $menu_more = 'Más';
    $menu_cancel = 'Cancelar';
    $menu_startchat = 'Comenzar Chat';
    $menu_resumechat = 'Reanudar  Chat';
    $menu_block = 'Bloquear';
    $menu_unblock = 'Desbloquear';
    
    $menu_signup = 'Registrarse';
    $menu_accept = 'Acepto los ';
    $menu_createaccount = 'Registrarse';
    $menu_login = "Iniciar Sesión";
    $menu_forgotpassword = 'Olvidé Contraseña';
    $menu_join = 'Unirse';
    $menu_existingaccount = 'Ya tiene una cuenta';
    $menu_or = 'o';
    $menu_e2ekey = 'E2E Secret Passkey - Optional';
    $menu_friends = "Amigos";
    $menu_friendadd = "Agrega Amigo";
    $menu_frienddelete = "Elimina Amigo";
    $menu_roomfavorite = "Añadir a favoritos";
    $menu_roomfavoritedelete = "Elimina favoritos";
    $menu_roomfavorites = "Salas Favoritas";
   
}

if($_SESSION['language']=='danish'){

    $menu_handle = 'Brugernavn';
    $menu_home = 'Hjem';
    $menu_rooms = 'Rum';
    $menu_room = 'Mine Rum';
    $menu_live = 'Live';
    $menu_chats = 'Samtaler';
    $menu_chat = 'Samtaler';
    $menu_people = 'Brugere';
    $menu_settings = 'Indstillinger';
    $menu_activity = 'Aktivitet';
    $menu_logout = 'Log Ud';
    $menu_restart = 'Genstart';
    $menu_myprofileandfiles = 'Min Profil, Fotos og Filer';
    $menu_myprofile = 'Min Profil';
    $menu_userprofile = "Brugerprofil";
    $menu_myphotos = 'Mine Fotos';
    $menu_myfiles = 'Mine Filer';
    $menu_myrooms = 'Mine Rum';
    $menu_whatsnew = "Hvad Nyt";
    $menu_password ='Password';
    $menu_confirmpassword ='Godkend Password';
    $menu_changepassword ='Skift Password';
    $menu_techsupport ='Teknisk Support';
    $menu_myaccountinfo = 'Mine Kontoinformationer';
    $menu_colortheme = 'Farvetema';
    $menu_language = 'Sprog Language';
    $menu_edit = 'Rediger';
    $menu_public = 'Offentlig';
    $menu_community = 'Fællesskab';
    $menu_top = 'Top';
    $menu_roomselect = 'Vælg Rum';
    $menu_discoverrooms = 'Opdage Rum';
    $menu_trending = 'Trending';
    $menu_communitylist = 'Fællesskabsliste';
    
    $menu_myidentity = 'Mit Identitet';
    $menu_mynotifications = 'Mine Notifkationer';
    $menu_advancedsettings = 'Avancerede Indstillinger';
    $menu_save = "Gem";
    $menu_managerooms = "Administrér Rum";
    $menu_manageroom = "Administrér Rum og Medlemmer";
    $menu_websites = "Websider";
    $menu_all = "Alt";
    $menu_activetoday = "Aktiv i Dag";
    $menu_sharefile = "Del Fil";
    $menu_photos = "Fotos";
    $menu_sharephoto = "Del Foto";
    $menu_uploadphoto = "Overfør Foto";
    $menu_uploadfile = "Overfør Fil";
    $menu_delete = "Slet";
    $menu_addparty = "Tilføj Party";
    $menu_station = "Station";
    $menu_startstation = 'Start Station';
    $menu_find = "Find";
    $menu_leave = "Forlade";
    $menu_back = "Tilbage";
    $menu_hide = "Skjul";
    $menu_gotoroom = "Gå til værelse for at skrive";
    $menu_name = 'Navn';
    $menu_email = 'Email';
    $menu_alias = 'Alias';
    $menu_platformtour = 'PlatformsTur';
    $menu_termsofuse = 'Vilkår for Anvendelse';
    $menu_privacy = 'Fortrolighedspolitik';
    $menu_tokenactivity = 'Token Aktivitet';
    $menu_tokenstore = 'Token Butik';
    $menu_sound = 'Lyd';
    $menu_deviceinfo = 'Bruger Device Info';
    
    $menu_tokens = 'Tokens';
    $menu_gift = 'Kudos!';
    $menu_thanks = 'Tak';
    
    $menu_whoshere = "Hvem er Her";
    $menu_roommembers = "Rum Medlemmer";
    $menu_aboutme = "Om Mig";
    $menu_managesocialvision = "Administrér $enterpriseapp";

    $menu_upgrade = "Opgrader Min Konto";
    $menu_setprofilephoto = "Indstil et Profilbillede";    
    $menu_biography = "Biografi";
    $menu_biographyprompt = "Biografi";
    $menu_refresh = "Opdater";
    $menu_title = 'Titel';
    $menu_newtopic = "Nyt emne - kommentar, link, video, billede";
    $menu_reply = "Svare";
    $menu_replies = "Meddelelser";
    $menu_roomfiles = "Rum Fil";
    $menu_roominvite = "Invitere";
    $menu_roomunsubscribe = "Opsige Abonnement";
    $menu_mutenotifications = "Stumme Notifkationer";
    $menu_unmutenotifications = "Aktiver Notifkationer";
    $menu_showoldermessages = "Vis gamle beskeder";
    $menu_hideoldermessages = "Skjul gamle beskeder";
    $menu_displayinglast = 'Viser de siste';
    $menu_messages = 'meddelelser';    
    $menu_message = 'meddelelser';    
    $menu_selectfile = 'Vælg Fil';
    $menu_selectphoto = 'Vælg Foto';
    $menu_takephoto = 'Venligst Foto';
    $menu_members = 'Medlemmer';
    $menu_pinned = 'Pinned';
    $menu_more = 'Mere';
    $menu_cancel = 'Afbestille';
    $menu_startchat = 'Start Samtaler';
    $menu_resumechat = 'Genoptag Samtaler';
    $menu_block = 'Blok';
    $menu_unblock = 'Fjerne Blok';
   
    $menu_signup = "Tilmeld Dig";
    $menu_accept = "Jeg accepterer ";
    $menu_createaccount = "Tilmeld Dig";
    $menu_login = "Logon";
    $menu_forgotpassword = 'Glemt Password';
    $menu_join = 'Slutte';
    $menu_existingaccount = 'Har du allerede en konto?';
    $menu_or = 'eller';
    $menu_e2ekey = 'E2E Secret Passkey - Optional';
    $menu_friends = "Venner";
    $menu_friendadd = "tilføj ven";
    $menu_frienddelete = "Fjern ven";
    $menu_roomfavorite = "Tilføj til favoritter";
    $menu_roomfavoritedelete = "Fjern fra favoritter";
    $menu_roomfavorites = "Yndlingsrum";
    
}
if($_SESSION['language']=='russian'){

    $menu_handle = 'имя пользователя';
    $menu_home = 'дом';
    $menu_rooms = 'комнаты';
    $menu_room = 'комната';
    $menu_live = 'Прямой эфир';
    $menu_chats = 'чаты';
    $menu_chat = 'чат';
    $menu_people = 'люди';
    $menu_settings = 'настройки';
    $menu_activity = 'деятельность';
    $menu_logout = 'выход из системы';

    $menu_restart = 'перезапуск';
    $menu_myprofileandfiles = 'Мой профиль, фотографии и файлы';
    $menu_myprofile= 'Мой профиль';
    $menu_userprofile = "Профиль пользователя";
    $menu_myphotos = 'мои фотографии';
    $menu_myfiles = 'мои файлы';
    $menu_myrooms = 'мои комнаты';
    $menu_whatsnew = "новости";
    $menu_password ='пароль';
    $menu_confirmpassword ='подтвердить пароль';
    $menu_changepassword ='сменить пароль';
    $menu_techsupport ='техническая поддержка';
    $menu_myaccountinfo = 'моя учетная запись';
    $menu_colortheme = 'обои';
    $menu_language = 'язык Language';
    $menu_edit = 'редактировать';
    $menu_public = 'общественности';
    $menu_community = 'сообщество';
    $menu_top = 'вверх';
    $menu_roomselect = 'выбрать комнату';
    $menu_discoverrooms = 'открыть комнаты';
    $menu_trending = 'популярный';
    $menu_communitylist = 'список сообщества';
    
    $menu_myidentity = 'моя личность';
    $menu_mynotifications = 'мои уведомления';
    $menu_advancedsettings = 'расширенные настройки';
    $menu_save = "сохранить изменения";
    $menu_managerooms = "управлять номерами";
    $menu_manageroom = "управлять комнатой и членами";
    $menu_websites = "сайты";
    $menu_all = "все";
    $menu_activetoday = "события сегодня";
    $menu_sharefile = "общий файл";
    $menu_photos = "фото";
   $menu_sharephoto = "поделиться фотографией";
    $menu_uploadphoto = "загрузить фото";
    $menu_uploadfile = "загрузить файл";
    $menu_delete = "удалять";
    $menu_addparty = "добавить пользователя";
    $menu_station = "станция";
    $menu_startstation = 'Начать станция';
    $menu_find = "найти";
    $menu_leave = "отпуск";
    $menu_back = "назад";
    $menu_hide = "скрывать";
    $menu_gotoroom = "Перейти в комнату для публикации";
    $menu_name = 'имя';
    $menu_email = 'по электронной почте';
    $menu_alias = 'псевдоним';
    $menu_platformtour = 'платформенный тур';
    $menu_termsofuse = 'Условия использования';
    $menu_privacy = 'Политика конфиденциальности';
    $menu_tokenactivity = 'Token деятельность';
    $menu_tokenstore = 'Token магазин';
    $menu_sound = 'звук';
    $menu_deviceinfo = 'пользовательское устройство';
    
    $menu_tokens = 'Tokens';
    $menu_gift = 'почет';
    $menu_thanks = 'спасибо';
    
    $menu_whoshere = "кто здесь";
    $menu_roommembers = "члены комнаты";
    $menu_aboutme = "обо мне";
    $menu_managesocialvision = "управлять $enterpriseapp";
    $menu_upgrade = "обновить аккаунт";
    $menu_setprofilephoto = "установить фотографию профиля";    
    $menu_biography = "биография";
    $menu_biographyprompt = "биография";
    $menu_refresh = "обновление";
    $menu_title = 'название';
    $menu_newtopic = "Новая тема, комментарий, ссылка, фотографии, видео";
    $menu_reply = "Ответить тему";
    $menu_replies = "комментарии";
    $menu_roomfiles = "файлы комнат";
    $menu_roominvite = "приглашать";
    $menu_roomunsubscribe = "отказаться от подписки";
    $menu_mutenotifications = "отключать оповещения";
    $menu_unmutenotifications = "включить уведомления";
    $menu_showoldermessages = "показать старые сообщения";
    $menu_hideoldermessages = "скрыть старые сообщения";
    $menu_displayinglast = 'отображение последних';
    $menu_messages = 'сообщений';    
    $menu_message = 'сообщений';    
    $menu_selectfile = 'выбрать файл';
    $menu_selectphoto = 'выбрать фото';
    $menu_takephoto = 'Фотографировать';
    $menu_members = 'члены';
    $menu_pinned = 'приколол';
    $menu_more = 'Больше';
    $menu_cancel = 'Отмена';
    $menu_startchat = 'Начать Чат';
    $menu_resumechat = 'возобновить чат';
    $menu_block = 'блок';
    $menu_unblock = 'открыть';
    
    $menu_signup = "зарегистрироваться";
    $menu_accept = "я принимаю ";
    $menu_createaccount = "зарегистрироваться";
    $menu_login = "Войти";
    $menu_forgotpassword = 'Забыли пароль';
    $menu_join = 'присоединиться';
    $menu_existingaccount = 'Already have an account?';
    $menu_or = 'или';
    $menu_e2ekey = 'E2E Secret Passkey - Optional';
    $menu_friends = "друзья";
    $menu_friendadd = "добавить друга";
    $menu_frienddelete = "удалить друга";
    $menu_roomfavorite = "добавить в избранное";
    $menu_roomfavoritedelete = "удалить из избранного";
    $menu_roomfavorites = "любимые номера";
    
}
if($_SESSION['language']=='dutch'){
    $menu_handle = "Gebruikersnaam";
    $menu_home = "Huis";
    $menu_rooms = "Kamers"; 
    $menu_room = "Kamer";
    $menu_live = "Live";
    $menu_chats = "Kouts"; 
    $menu_chat = "Chat";
    $menu_people = "Mensen"; 
    $menu_settings = "Instellingen"; 
    $menu_activity = "Activiteit";
    $menu_logout = "Uitloggen";
    $menu_restart = "Herstarten"; 
    $menu_myprofileandfiles = "Mijn Profiel, Foto's en Bestanden"; 
    $menu_myprofile = "Mijn Profiel"; 
    $menu_userprofile = "Gebruikersprofiel";
    $menu_myphotos = "Mijn Foto's";
    $menu_myfiles = "Mijn Bestanden"; 
    $menu_myrooms = "Mijn Kamers"; 
    $menu_whatsnew = "Wat is Nieuw"; 
    $menu_password = "Wachtwoord"; 
    $menu_confirmpassword = "Bevestig Wachtwoord";
    $menu_changepassword ="Verander Wachtwoord"; 
    $menu_techsupport = "Technische Ondersteuning"; 
    $menu_myaccountinfo = "Mijn Account Informatie"; 
    $menu_colortheme = "Kleur Thema";

    $menu_language = "Taal Language";
    $menu_edit = "Bewerk"; 
    $menu_public = "Publiek"; 
    $menu_community = "Gemeenschap"; 
    $menu_top = "Top"; 
    $menu_roomselect = "Kiezen Kamer";
    $menu_trending = "Trending"; 
    $menu_communitylist = "Gemeenschap Lijsten";

    $menu_myidentity = "Mijn Identiteit"; 
    $menu_mynotifications = "Mijn Meldingen";
    $menu_advancedsettings = "Geavanceerde Instellingen";
    $menu_save = "Wijzigingen Opslaan"; 
    $menu_managerooms = "Beheer Kamers"; 
    $menu_websites = "Websites"; 
    $menu_all = "Alle"; 
    $menu_activetoday = "Vandaag Actief";
    $menu_sharefile = "Deel Bestand";
    $menu_photos = "Fotos"; 
    $menu_sharephoto = "Deel Foto"; 
    $menu_uploadphoto = "Uploaden Foto"; 
    $menu_uploadfile = "Uploaden Bestand"; 
    $menu_delete = "Verwijderen"; 
    $menu_addparty = "Groep Toevoegen"; 
    $menu_station = "Station"; 
    $menu_startstation = 'Begin Station';
    $menu_leave = "Verlaten"; 
    $menu_back = "Terug";
    $menu_hide = "Verbergen";
    $menu_name = "Naam"; 
    $menu_email = "Email"; 
    $menu_alias = "Externe Alias"; 
    $menu_platformtour = "Platform Tour"; 
    $menu_termsofuse = "Gebruiksvoorwaarden"; 
    $menu_privacy = "Privacy Beleid"; 
    $menu_tokenactivity = "Token Activiteit"; 
    $menu_tokenstore = "Token Winkel"; 
    $menu_sound = "Geluid"; 
    $menu_deviceinfo = "Gebruikersapparaatinfo"; 

    $menu_tokens = "Tokens"; 
    $menu_gift = "Kudos!"; 
    $menu_thanks = "Dankje!"; 

    $menu_whoshere = "Wie is Hier";
    $menu_aboutme = "Over Mij"; 
    $menu_managesocialvision = "Beheer $enterpriseapp"; 
    $menu_upgrade = "Upgrade Account to $enterpriseapp";
    $menu_setprofilephoto = "Set a Profile Photo";    
    $menu_biography = "Biografie";
    $menu_biographyprompt = "Biografie";
    $menu_refresh = "Verversen";
    $menu_title = 'Titel';
    $menu_newtopic = "Nieuw onderwerp, commentaar, link, fotos, video";
    $menu_reply = "Onderwerp antwoord";
    $menu_replies = "Opmerkingen";
    $menu_roomfiles = "Kamer Bestanden";
    $menu_roominvite = "Nodig uit";
    $menu_roomunsubscribe = "Abonnement op de kamer opzeggen";
    $menu_mutenotifications = "Meldingen dempen";
    $menu_unmutenotifications = "Meldingen toestaan";
    $menu_showoldermessages = "Toon oudere berichten";
    $menu_hideoldermessages = "Verberg oudere berichten";
    $menu_displayinglast = 'laatste berichten weergeven';
    $menu_messages = 'berichten';    
    $menu_message = 'Bericht';    
    $menu_selectfile = 'Selecteer Bestand';
    $menu_selectphoto = 'Selecteer Foto';
    $menu_takephoto = 'Maak een Foto';
    $menu_members = 'Leden';
    $menu_pinned = 'Gespeld';
    $menu_more = 'Meer';
    $menu_cancel = 'Annuleer';
    $menu_startchat = 'Begin Chat';
    $menu_resumechat = 'Ga Door Chat';
    $menu_block = 'Blok';
    $menu_unblock = 'Deblokkeren';
    
    $menu_signup = "Meld je Aan";
    $menu_accept = "ik accepteer de ";
    $menu_createaccount = "Meld je aan";
    $menu_login = "Login";
    $menu_forgotpassword = 'Wachtwoord Vergeten';
    $menu_join = 'Toetreden';
    $menu_existingaccount = 'Heb al een account';
    $menu_or = 'of';
    $menu_e2ekey = 'E2E Secret Passkey - Optional';
    $menu_friends = "Vrienden";
    $menu_friendadd = "Vriend toevoegen";
    $menu_frienddelete = "Vriend verwijderen";
    $menu_roomfavorite = "Toevoegen aan favorieten";
    $menu_roomfavoritedelete = "Verwijder van favorieten";
    $menu_roomfavorites = "Favoriete kamers";
    
}
if($_SESSION['language']=='french'){

    $menu_handle = "Nom d'utilisateur";
    $menu_home = 'Accueil';
    $menu_rooms = 'Pièces';
    $menu_room = 'Pièce';
    $menu_live = 'Direct';
    $menu_chats = 'Messageries';
    $menu_chat = 'Messagerie';
    $menu_people = 'Gens';
    $menu_settings = 'Réglage';
    $menu_activity = 'Activité';
    $menu_logout = 'Connectez - Out';
    $menu_restart = 'Redémarrer';
    $menu_myprofileandfiles = 'Mon profil, Photos, Dossiers';
    $menu_myprofile = 'Mon profil';
    $menu_userprofile = "Profil de l'Utilisateur";
    $menu_myphotos = 'Mes Photos';
    $menu_myfiles = 'Mes Dossiers';
    $menu_myrooms = 'Mes Pièces';
    $menu_whatsnew = "Quoi de Neuf";
    $menu_password ='Mot de Passe';
    $menu_confirmpassword ='Confirmez le Mot de Passe';
    $menu_changepassword ='Changer le Mot de Passe';
    $menu_techsupport ='Support Technique';
    $menu_myaccountinfo = 'Mon compte Info';
    $menu_colortheme = 'Thème de Couleur';
    $menu_language = 'Langue';
    $menu_edit = 'Modifier';
    $menu_public = 'Publique';
    $menu_community = 'Communauté';
    $menu_top = 'Haut';
    $menu_roomselect = 'Sélectionner Pièce';
    $menu_discoverrooms = 'Découvrir des Pièces';
    $menu_trending = 'Populaire';
    $menu_communitylist = 'Liste Communautaire';
    
    $menu_myidentity = 'Mon Identité';
    $menu_mynotifications = 'Mon Notifications';
    $menu_advancedsettings = 'Réglages avancés';
    $menu_save = "Sauvegarder les Modifications";
    $menu_managerooms = "Gérer les Pièces";
    $menu_manageroom = "Gérer la Pièce et Membres";
    $menu_websites = "Sites Internet";
    $menu_all = "Tout";
    $menu_activetoday = "Actif Aujourd'hui";
    $menu_sharefile = "Partager Dossier";
    $menu_photos = "Photos"; 
    $menu_sharephoto = "Partager Photo";
    $menu_uploadphoto = "Téléverser Photo";
    $menu_uploadfile = "Téléverser Dossier";
    $menu_delete = "Effacer";
    $menu_addparty = "Ajouter Personne";
    $menu_station = "Canal";
    $menu_startstation = "Commencer Canal";
    $menu_find = "Trouver";
    $menu_leave = "Laisser";
    $menu_back = "Arrière";
    $menu_hide = "Cacher";
    $menu_gotoroom = "Aller à la pièce pour poster";
    $menu_name = 'Prénom';
    $menu_email = 'Email';
    $menu_alias = 'Alias';
    $menu_platformtour = 'Tour de Plateforme';
    $menu_termsofuse = "Conditions d'Utilisation";
    $menu_privacy = 'Politique de Confidentialité';
    $menu_tokenactivity = 'Activité Token';
    $menu_tokenstore = 'Magasin Token';
    $menu_sound = 'Son';
    $menu_deviceinfo = 'Périphérique Utilisateur';
    
    $menu_tokens = 'Tokens';
    $menu_gift = 'Gloire!';
    $menu_thanks = 'Merci!';
    
    $menu_whoshere = "Qui est là";
    $menu_roommembers = "Members Pièce";
    $menu_aboutme = "À propos de Moi";
    $menu_managesocialvision = "Gérer $enterpriseapp";
    $menu_upgrade = "Améliorer le Compte";
    $menu_setprofilephoto = "Définir une Photo de Profil";    
    $menu_biography = "Biographie";
    $menu_biographyprompt = "Biographie";
    $menu_refresh = "Rafraîchir";
    $menu_title = 'Titre';
    $menu_newtopic = "Nouveau sujet - commentaire, lien, photos, vidéo";
    $menu_reply = "Topic Reply";
    $menu_replies = "Commentaires";
    $menu_roomfiles = "Dossiers Pièce";
    $menu_roominvite = "Inviter";
    $menu_roomunsubscribe = "Désabonnement";
    $menu_mutenotifications = "Masquer Notifications";
    $menu_unmutenotifications = "Activer Notifications";
    $menu_showoldermessages = "Ancien Messages";
    $menu_hideoldermessages = "Cacher messages plus anciennes";
    $menu_displayinglast = 'Affichant les';
    $menu_messages = 'Messageries';    
    $menu_message = 'Messagerie';    
    $menu_selectfile = 'Choiser Dossier';
    $menu_selectphoto = 'Choiser Photo';
    $menu_takephoto = 'Prendre Photo';
    $menu_members = 'Membres';
    $menu_pinned = 'épinglé';
    $menu_more = 'Plus';
    $menu_cancel = 'Annuler';
    $menu_startchat = 'Commencer Messagerie';
    $menu_resumechat = 'Reprendre Messagerie';
    $menu_block = 'Bloc';
    $menu_unblock = 'Débloquer';
    
    $menu_signup = "s'Inscrire";
    $menu_accept = "J'accepte les ";
    $menu_createaccount = "s'inscrire";
    $menu_login = "Login";
    $menu_forgotpassword = 'Oublié Mot de Passe';
    $menu_join = 'Rejoindre';
    $menu_existingaccount = 'Avez déjà un compte';
    $menu_or = 'ou';
    $menu_e2ekey = 'E2E Secret Passkey - Optional';
    $menu_friends = "Amis";
    $menu_friendadd = "Ajouter un Ami";
    $menu_frienddelete = "Enlever un ami";
    $menu_roomfavorite = "Ajouter aux favoris";
    $menu_roomfavoritedelete = "Enlever un favoris";
    $menu_roomfavorites = "Pièces Favoris";
    
}
if($_SESSION['language']=='korean'){

    $menu_handle = '사용자 이름'; 
    $menu_home = '홈페이지'; 
    $menu_rooms = '방'; 
    $menu_room = '방'; 
    $menu_live = '라이브'; 
    $menu_chats = '담잡'; 
    $menu_chat = '담잡'; 
    $menu_people = '사람들'; 
    $menu_settings = '설정'; 
    $menu_activity = '활동'; 
    $menu_logout = '로그아웃'; 
    $menu_restart = '재시작'; 
    $menu_myprofileandfiles = '제 프로필, 사진, 과 서류들'; 
    $menu_myprofile = '제 프로필'; 
    $menu_userprofile = "유저 프로필"; 
    $menu_myphotos = '제사진'; 
    $menu_myfiles = '제 서류들'; 
    $menu_myrooms = '제 방'; 
    $menu_whatsnew = "별일 없어요"; 
    $menu_password ='비밀번호'; 
    $menu_confirmpassword ='비밀번호 확인'; 
    $menu_changepassword ='비밀번호 변경'; 
    $menu_techsupport ='기술 지원'; 
    $menu_myaccountinfo = '제 계정 정보'; 
    $menu_colortheme = '배경색'; 
    $menu_language = '언어'; 
    $menu_edit = '바꾸'; 
    $menu_public = '공공합니'; 
    $menu_community = '군서'; 
    $menu_top = '상단'; 
    $menu_roomselect = '방 선택'; 
    $menu_trending = '현재 인기있는'; 
    $menu_communitylist = '집단 옵션들'; 
    $menu_myidentity = '제 정체성'; 
    $menu_mynotifications = '제 알림'; 
    $menu_advancedsettings = '고급 설정'; 
    $menu_save = "변경 사항을 저장하다"; 
    $menu_managerooms = "객실 관리"; 
    $menu_websites = "웹 사이트"; 
    $menu_all = "다"; 
    $menu_activetoday = "액티브 투데이"; 
    $menu_sharefile = "몫 서류들"; 
    $menu_sharephoto = "몫 사진"; 
    $menu_uploadphoto = "사진 업로드"; 
    $menu_uploadfile = "서류들 업로드"; 
    $menu_delete = "지우다"; 
    $menu_addparty = "파티 추가"; 
    $menu_station = "방송국"; 
    $menu_startstation = '채팅 시작'; //Needs Redo
    $menu_leave = "출구"; 
    $menu_back = "뒤로";
    $menu_hide = "숨는 장소";
    $menu_name = '이름'; 
    $menu_email = '이메일'; 
    $menu_alias = '외부 별칭'; 
    $menu_platformtour = '플랫폼 둘러보기'; 
    $menu_termsofuse = '이용 약관'; 
    $menu_privacy = '개인 정보 정책'; 
    $menu_tokenactivity = '토큰 활동'; 
    $menu_tokenstore = '토큰 상점'; 
    $menu_sound = '음성'; 
    $menu_deviceinfo = '사용자 장치 정보'; 

    $menu_tokens = '토큰'; 
    $menu_gift = '명성!'; 
    $menu_thanks = '감사합니다'; 

    $menu_whoshere = "누구여기야"; 
    $menu_aboutme = "나에 대해서"; 
    $menu_managesocialvision = "사회적인 시력 조절하여"; 
    $menu_upgrade = "업그레이드 계정"; 
    $menu_setprofilephoto = "프로필 사진 설정"; 
    $menu_biography = "전기문학";
    $menu_biographyprompt = "전기문학";
    $menu_refresh = "새롭게 하다";
    $menu_title = '표제';
    $menu_newtopic = "새로운 화제, 연결, 사진, 영상";
    $menu_reply = "주제 응답";
    $menu_replies = "코멘트";
    $menu_roomfiles = "Room Files";
    $menu_roominvite = "초대";
    $menu_roomunsubscribe = "구독 취소";
    $menu_mutenotifications = "알림 음소거";
    $menu_unmutenotifications = "알림 사용";
    $menu_showoldermessages = "오래된 메시지보기";
    $menu_hideoldermessages = "오래된 메시지 숨기기";
    $menu_displayinglast = '개 표시';
    $menu_messages = '메시지';    
    $menu_message = '메시지';    
    $menu_selectfile = '파일 선택';
    $menu_selectphoto = '사진 선택';
    $menu_takephoto = '사진을 찍다';
    $menu_members = '회원';
    $menu_pinned = '고정 된';
    $menu_more = '더';
    $menu_cancel = '취소';
    $menu_startchat = '채팅 시작';
    $menu_resumechat = '채팅 재개';
    $menu_block = '블록';
    $menu_unblock = '차단 해제하다';
    
    $menu_signup = "가입하다";
    $menu_accept = "나는 동의한다 ";
    $menu_createaccount = "계정 만들기";
    $menu_login = "로그인";
    $menu_forgotpassword = '비밀번호를 잊으 셨나요';
    $menu_join = '가입';
    $menu_existingaccount = '이미 계정이있다';
    $menu_or = '또는';    
    $menu_e2ekey = 'E2E Secret Passkey - Optional';
    $menu_friends = "Friends";
    $menu_friendadd = "Add Friend";
    $menu_frienddelete = "Remove Friend";
    $menu_roomfavorite = "Add Room to Favorites";
    $menu_roomfavoritedelete = "Remove Room from Favorites";
    $menu_roomfavorites = "Favorite Rooms";
}
if($_SESSION['language']=='german'){

    $menu_handle = 'Nutzername';
    $menu_home = 'Startseite';
    $menu_rooms = 'Räume';
    $menu_room = 'Raum';
    $menu_live = 'Live';
    $menu_chats = 'Chats';
    $menu_chat = 'Chat';
    $menu_people = 'Menschen';
    $menu_settings = 'Einstellungen';
    $menu_activity = 'Aktivität';
    $menu_logout = 'Ausloggen';
    $menu_restart = 'Neustart';
    $menu_myprofileandfiles = 'Mein Profil, Fotos, Dokumente';
    $menu_myprofile = 'Mein Profil';
    $menu_userprofile = "Benutzerprofil";
    $menu_myphotos = 'Meine Fotos';
    $menu_myfiles = 'Meine Dokumente';
    $menu_myrooms = 'Meine Räume';
    $menu_whatsnew = "Was gibt's Neues";
    $menu_password ='Passwort';
    $menu_confirmpassword ='Bestätige Passwort';
    $menu_changepassword ='Passwort ändern';
    $menu_techsupport ='Technischer Support';
    $menu_myaccountinfo = 'Meine Accountinformationen';
    $menu_colortheme = 'Farbthema';
    $menu_language = 'Sprache';
    $menu_edit = 'Bearbeiten';
    $menu_public = 'Öffentlichkeit';
    $menu_community = 'Gemeinschaft';
    $menu_top = 'Geehrt';
    $menu_roomselect = 'Raume Wählen';
    $menu_discoverrooms = 'Raume Entdecken';
    $menu_trending = 'Beliebt';
    $menu_communitylist = 'Gemeinschaftslisten';
    
    $menu_myidentity = 'Meine Identität';
    $menu_mynotifications = 'Meine Benachrichtigungen';
    $menu_advancedsettings = 'Erweiterte Einstellungen';
    $menu_save = "Änderungen Speichern";
    $menu_managerooms = "Räume Verwalten";
    $menu_manageroom = "Raume und Mitglieder Verwalten";
    $menu_websites = "Websites";
    $menu_all = "Alle";
    $menu_activetoday = "Aktiv Heute";
    $menu_sharefile = "Dokumente Teilin";
    $menu_photos = "Fotos"; 
    $menu_sharephoto = "Foto Teilin";
    $menu_uploadphoto = "Foto Hochladen";
    $menu_uploadfile = "Dokumente Hochladen";
    $menu_delete = "Löschen";
    $menu_addparty = "Person Hinzufügen";
    $menu_station = "Station";
    $menu_startstation = 'Station Beginnen';
    $menu_find = "Finden";
    $menu_leave = "Verlassen";
    $menu_back = "Zurück";
    $menu_hide = "Verbergen";
    $menu_gotoroom = "Gehe in das Raume, um es zu posten";
    $menu_name = 'Name';
    $menu_email = 'Email';
    $menu_alias = 'Alias';
    $menu_platformtour = 'Plattform-Tour';
    $menu_termsofuse = 'Nutzungsbedingungen';
    $menu_privacy = 'Datenschutz-Bestimmungen';
    $menu_tokenactivity = 'Token-Aktivität';
    $menu_tokenstore = 'Token-Speicher';
    $menu_sound = 'Klingen';
    $menu_deviceinfo = 'Benutzergerät-Info';
    
    $menu_tokens = 'Tokens';
    $menu_gift = 'Kudos!';
    $menu_thanks = 'Danke!';
    
    $menu_whoshere = "Wer ist Hier";
    $menu_roommembers = "Raume Mitglieder";
    $menu_aboutme = "über mich";
    $menu_managesocialvision = "Verwalten $enterpriseapp";
    $menu_upgrade = "Konto Aktualisieren";
    $menu_setprofilephoto = "Legen Sie ein Profilfoto Fest";    
    $menu_biography = "Biografie";
    $menu_biographyprompt = "Biografie";
    $menu_refresh = "Aktualisieren";
    $menu_title = 'Titel';
    $menu_newtopic = "Neues Thema, Kommentar, Link, Fotos, Video";
    $menu_reply = "Themenantwort";
    $menu_replies = "Bemerkungen";
    $menu_roomfiles = "Raumdokumente";
    $menu_roominvite = "Einladen";
    $menu_roomunsubscribe = "Raume Abmelden";
    $menu_mutenotifications = "Benachrichtigungen stummschalten";
    $menu_unmutenotifications = "Benachrichtigungen aktivieren";
    $menu_showoldermessages = "Zeige ältere Nachrichten";
    $menu_hideoldermessages = "Altere Nachrichten Ausblenden";
    $menu_displayinglast = 'Anzeige der letzten';
    $menu_messages = 'Nachrichten';    
    $menu_message = 'Nachrichten';    
    $menu_selectfile = 'Dokumente Aussuchen';
    $menu_selectphoto = 'Foto Aussuchen';
    $menu_takephoto = 'Foto Machen';
    $menu_members = 'Mitglieder';
    $menu_pinned = 'Gepinnt';
    $menu_more = 'Mehr';
    $menu_cancel = 'Stornieren';
    $menu_startchat = 'Chat Beginnen';
    $menu_resumechat = 'Chat Fortsetzen';
    $menu_block = 'Blockieren';
    $menu_unblock = 'Entsperren';
    
    $menu_signup = "Melde dich an";
    $menu_accept = "Ich akzeptiere die ";
    $menu_createaccount = "Konto erstellen";
    $menu_login = "Login";
    $menu_forgotpassword = 'Passwort Vergessen';
    $menu_join = 'Beitreten';
    $menu_existingaccount = 'Hast du schon ein Konto';
    $menu_or = 'oder';
    $menu_e2ekey = 'E2E Secret Passkey - Optional';
    $menu_friends = "Freunde";
    $menu_friendadd = "Freunde hinzufügen";
    $menu_frienddelete = "Freund löschen";
    $menu_roomfavorite = "Favoriten hinzufügen";
    $menu_roomfavoritedelete = "Favoriten entfernen";
    $menu_roomfavorites = "Raum-Favoriten";
    
}
if($_SESSION['language']=='portuguese'){

    $menu_handle = 'Nome de Usuário';
    $menu_home = 'Lar';
    $menu_rooms = 'Salas';
    $menu_room = 'Sala';
    $menu_live = 'Canal';
    $menu_chats = 'Chat';
    $menu_chat = 'Chat';
    $menu_people = 'Pessoas';
    $menu_settings = 'Configuração';
    $menu_activity = 'Notificações';
    $menu_logout = 'Fechar Sessão';
    $menu_restart = 'Reiniciar';
    $menu_myprofileandfiles = 'Meu perfil, fotos e arquivos';
    $menu_myprofile = 'Meu perfil';
    $menu_userprofile = "Perfil de Usuário";
    $menu_myphotos = 'Minhas Fotos';
    $menu_myfiles = 'Minhas Arquivos';
    $menu_myrooms = 'Minhas Salas';
    $menu_whatsnew = "Que há de novo";
    $menu_password ='Senha';
    $menu_confirmpassword ='Confirme Senha';
    $menu_changepassword ='Mudar Senha';
    $menu_techsupport ='Suporte técnico';
    $menu_myaccountinfo = 'Minha informação';
    $menu_colortheme = 'Tema de Cor';
    $menu_language = 'Idioma Language';
    $menu_edit = 'Editar';
    $menu_public = 'Público';
    $menu_community = 'Communidade';
    $menu_top = "Honrado";
    $menu_roomselect = 'Seleção  de Salas';
    $menu_discoverrooms = 'Discubra Salas';
    $menu_trending = 'Popular';
    $menu_communitylist = 'Lista de Communidades';
        
    $menu_myidentity = 'Minha Identidade';
    $menu_mynotifications = 'Minhas notificações';
    $menu_advancedsettings = 'Configurações Avançadas';
    $menu_save = "Salva Alterações";
    $menu_managerooms = "Gerenciar Salas";
    $menu_manageroom = "Gerenciar Sala e Membros";
    $menu_websites = "Site da Internet";
    $menu_all = "Todos";
    $menu_activetoday = "Ativo Hoje";
    $menu_sharefile = "Compartilha Arquivo";
    $menu_photos = "Fotos";
    $menu_sharephoto = "Compartilha Foto";
    $menu_uploadphoto = "Carregar Foto";
    $menu_uploadfile = "Carregar Arquivo";
    $menu_delete = "Excluir";
    $menu_addparty = "Adicionar Pessoa";
    $menu_station = "Canal";
    $menu_startstation = 'Iniciar Canal';
    $menu_find = "Buscar";
    $menu_leave = "Sair";
    $menu_back = "Atrás";
    $menu_hide = "Esconda";
    $menu_gotoroom = "vá para sala para publicar";
    $menu_name = 'Nome';
    $menu_email = 'Email';
    $menu_alias = 'Alias';
    $menu_platformtour = 'Toro de la Plataforma';
    $menu_termsofuse = 'Condições de Uso';
    $menu_privacy = 'Política de Privacidade';
    $menu_tokenactivity = 'Atividade de Token';
    $menu_tokenstore = 'Loja de Token';
    $menu_sound = 'Som';
    $menu_deviceinfo = 'informação Dispostivo';
    
    $menu_tokens = 'Tokens';
    $menu_gift = 'Crédito';
    $menu_thanks = 'Obrigado';
    
    $menu_whoshere = "Quem está aqui";
    $menu_roommembers = "Membros de Sala";
    $menu_aboutme = "Sobre Mim";
    $menu_managesocialvision = "Gerenciar $enterpriseapp";
    $menu_upgrade = "Atualizar conta";
    $menu_setprofilephoto = "Definir foto do perfil";    
    $menu_biography = "Biografia";
    $menu_biographyprompt = "Biografia";
    $menu_refresh = "Refresca";
    $menu_title = 'Título';
    $menu_newtopic = "Novo tópico, comentários, fotos, links, arquivos";
    $menu_reply = "Resposta do tópico";
    $menu_replies = "Respostas";
    $menu_roomfiles = "Arquivo de Salas";
    $menu_roominvite = "Convite";
    $menu_roomunsubscribe = "Sair de Sala";
    $menu_mutenotifications = "Silêncio Notificações";
    $menu_unmutenotifications = "Permitir notificações";
    $menu_showoldermessages = "Mostra Mensagens Antigas";
    $menu_hideoldermessages = "Esconde Mensagens Antigas";
    $menu_displayinglast = 'Mostrando los últimos';
    $menu_messages = 'Mensagens';    
    $menu_message = 'Mensagen';    
    $menu_selectfile = 'Selecione Arquivo';
    $menu_selectphoto = 'Selecione Foto';
    $menu_takephoto = 'Tira Foto';
    $menu_members = 'Membros';
    $menu_pinned = 'Pregar';
    $menu_more = 'Mais';
    $menu_cancel = 'Cancelar';
    $menu_startchat = 'Iniciar Chat';
    $menu_resumechat = 'Retomar  Chat';
    $menu_block = 'Bloquear';
    $menu_unblock = 'Desbloquear';
    
    $menu_signup = 'Inscrição';
    $menu_accept = 'Aceita os ';
    $menu_createaccount = 'Inscrição';
    $menu_login = "Iniciar Sessão";
    $menu_forgotpassword = 'Esqueceu a Senha';
    $menu_join = 'Junta';
    $menu_existingaccount = 'Eu tenho uma conta existente';
    $menu_or = 'ou';
    $menu_e2ekey = 'E2E Secret Passkey - Optional';
    $menu_friends = "Amigos";
    $menu_friendadd = "Adicionar Amigo";
    $menu_frienddelete = "Remover Amigo";
    $menu_roomfavorite = "Adicionar aos favoritos";
    $menu_roomfavoritedelete = "Remover dos favoritos";
    $menu_roomfavorites = "Sala Favoritos";
   
}
if($_SESSION['language']=='urdu'){

    $menu_handle = 'Username';
    $menu_home = 'Ghar';
    $menu_rooms = 'Kamra ';
    $menu_room = 'Kamray ';
    $menu_live = 'Live';
    $menu_chats = 'Baat Cheet';
    $menu_chat = 'Baat';
    $menu_people = 'Lok ';
    $menu_settings = 'Settings';
    $menu_activity = 'Josh';
    $menu_logout = 'Logout';
    $menu_restart = 'Restart';
    $menu_myprofile = 'Meri Profile';
    $menu_userprofile = "User Profile";
    $menu_myphotos = 'Meri Photo';
    $menu_myfiles = 'Meri Files';
    $menu_myrooms = 'Ye Meray Kamray';
    $menu_whatsnew = "Tazaa";
    $menu_password ='Password';
    $menu_confirmpassword ='Tasdeeq Password';
    $menu_changepassword ='Badloh Password';
    $menu_techsupport ='Tech Support';
    $menu_myaccountinfo = 'Mera Account Info';
    $menu_colortheme = 'Rang Mozo';
    $menu_language = 'Urdu';
    $menu_edit = 'Edit';
    $menu_public = 'Public';
    $menu_community = 'Community';
    $menu_top = 'Oopar';
    $menu_roomselect = 'Chunna Kamra';
    $menu_discoverrooms = 'Daryaaft Kamray';
    $menu_trending = 'Trending';
    $menu_communitylist = 'Firqaa Fehrist';
    $menu_myidentity = 'Meri Pehchan';
    $menu_mynotifications = 'Meri Itlah ';
    $menu_advancedsettings = 'Advanced Settings';
    $menu_save = "Save Tabdeel";
    $menu_managerooms = "Intezaam Kamray";
    $menu_manageroom = "Intezaam Kamra Aur Rukun";
    $menu_websites = "Websites";
    $menu_all = "Sab";
    $menu_activetoday = "Active Aaj";
    $menu_sharefile = "Share File";
    $menu_photos = "Tasveer";
    $menu_sharephoto = "Share Tasveer";
    $menu_uploadphoto = "Upload Tasveer";
    $menu_uploadfile = "Upload File";
    $menu_delete = "Delete";
    $menu_addparty = "Add Party";
    $menu_station = "Station";
    $menu_startstation = 'Shuru Station';
    $menu_find = "Dundnah";
    $menu_leave = "Chor Doh";
    $menu_back = "Peechay";
    $menu_hide = "Chupana";
    $menu_gotoroom = "Kamray main Jao Aur post Choro";
    $menu_name = 'Naam';
    $menu_email = 'Email';
    $menu_alias = 'External Alias';
    $menu_platformtour = 'Platform Tour';
    $menu_termsofuse = 'Terms of Use';
    $menu_privacy = 'Privacy Policy';
    $menu_tokenactivity = 'Token Activity';
    $menu_tokenstore = 'Token Store';
    $menu_sound = 'Awaaz';
    $menu_deviceinfo = 'User Device Info';
}

function InternationalizeDate($date){
    if($_SESSION['language']=='english'){
        return $date;
    }
    if($date == ''){
        return "";
    }
    $timepart = explode(" ",$date);
    $datepart = explode("/",$timepart[0]);
    $year = "";
    if(isset($datepart[2])){
        $year = $datepart[2];
    }
    if($year!=''){
        $year = '/'.$year;
    }
    if( !isset($timepart[1])){
        $timepart[1]='';
    }
    $newdate = $datepart[1]."/".$datepart[0].$year." ".$timepart[1];
    return $newdate;
}
function GetLanguageArray()
{
    $language[0]='english';
    $language[1]='english-uk';
    $language[2]='danish';
    $language[3]='dutch';
    $language[4]='french';
    $language[5]='german';
    $language[6]='korean';
    $language[7]='russian';
    $language[8]='spanish';
    $language[9]='portuguese';
    $language[10]='urdu';
    
    return  $language;
    
}
function GetLanguageLabelArray()
{
    $languagelabel[0]='English';
    $languagelabel[1]='English-UK';
    $languagelabel[2]='Dansk';
    $languagelabel[3]='Nederlands';
    $languagelabel[4]='Français';
    $languagelabel[5]='Deutsch';
    $languagelabel[6]='한국어';
    $languagelabel[7]='русский';
    $languagelabel[8]='Español';
    $languagelabel[9]='Português';
    $languagelabel[10]='Urdu';
    

    return $languagelabel;
}
function LanguageLinks($link, $style, $color){
    global $customsite;
    if($customsite){
        return "";
    }
    
    $language = GetLanguageArray();
    $languagelabel = GetLanguageLabelArray();
    
    $i =0;
    $bar = "";
    for($i=0;$i<10;$i++){
        $bar.="<div class='mainfont' style='height:20px;position:relative;$style;white-space:nowrap;padding:5px'><a href='$link&lang=$language[$i]' style='text-decoration:none;color:$color'>$languagelabel[$i]</a>&nbsp;</div>";
    }
    return $bar;
}

/*

Home (page) - página web 
People - personas 
Live - canal (means channel, as in television) 
Chat (room) - sala de chat 
(my) Rooms - mi salas 

Settings - configuración 
Logout - Salir (means leave) 

Login - acceso 
*/

?>