<?php
echo "<!DOCTYPE html>\r\n";
echo "<html>\r\n";
echo "<head>\r\n";
echo "<link rel='stylesheet' href='https://www.braxsecure.com/smsg/libs/jquery-1.9.0/jquery-ui.css' type='text/css' />\r\n";
echo "<link rel='styleSheet' href='https://www.braxsecure.com/smsg/local.css' type='text/css'/>\r\n";
echo "<link rel='shortcut icon' href='https://www.braxsecure.com/home_files/favicon.ico' type='image/x-icon'>\r\n";
echo "<link rel='apple-touch-icon' href='https://www.braxsecure.com/home_files/favicon.ico'>\r\n";
echo "\r\n";
echo "\r\n";
echo "<script src='https://www.braxsecure.com/smsg/libs/jquery-1.9.0/jquery.min.js'></script>\r\n";    
echo "<script src='https://www.braxsecure.com/smsg/libs/jquery-cookie-master/jquery.cookie.js'></script>\r\n";
echo "\r\n";
echo "\r\n";
echo "<script src='https://www.braxsecure.com/smsg/libs/dist/jquery.validate.js'></script>\r\n";
echo "<script src='https://www.braxsecure.com/smsg/libs/dist/jquery.validate.min.js'></script>\r\n";
echo "<script src='https://www.braxsecure.com/smsg/libs/dist/additional-methods.js'></script>\r\n";
echo "<script src='https://www.braxsecure.com/smsg/libs/dist/additional-methods.min.js'></script>\r\n";
echo "</head>\r\n";
?>
